name = "sk-local-server"

node_compat = true
compatibility_flags = [ "nodejs_compat" ]


[[d1_databases]]
binding = "SK_DB"
database_name = "sk_rep"
database_id = "51e74355-6cba-4b07-9f72-86d71ea1b4e4"
